"use client";
import "./dispatch.css";
import {useEffect,useMemo,useState} from "react";
import {dispatchDecision} from "../../../lib/dispatch";
import {assignCourierToOrder,loadMvp,recordDispatchOffer,resolveDispatchOffer,subscribeOrders} from "../../../lib/mvp-store.js";
import {loadCouriers,subscribeCouriers,updateCourier} from "../../../lib/courier-registry.js";
const cashMethod=value=>String(value||"").toLowerCase().includes("efectivo")?"cash":"card";
export default function Dispatch(){
 const[couriers,setCouriers]=useState([]),[orders,setOrders]=useState([]),[selectedId,setSelectedId]=useState(null),[seconds,setSeconds]=useState(25),[notice,setNotice]=useState("");
 useEffect(()=>{const refresh=()=>setCouriers(loadCouriers());refresh();return subscribeCouriers(refresh)},[]);
 useEffect(()=>{const refresh=()=>{const pending=loadMvp().orders.filter(o=>["Listo","Esperando repartidor"].includes(o.status)&&!o.courierId);setOrders(pending);setSelectedId(id=>pending.some(o=>o.id===id)?id:(pending[0]?.id||null))};refresh();return subscribeOrders(refresh)},[]);
 const order=orders.find(o=>o.id===selectedId)||null;
 const dispatchOrder=useMemo(()=>order?{paymentMethod:cashMethod(order.paymentMethod),totalCents:Math.round((Number(order.total)||0)*100),courierEarningCents:Math.round((Number(order.courierEarning)||0)*100),routeFitByCourier:{},extraPickupMinutes:0,extraDeliveryMinutes:0}:null,[order]);
 const decision=useMemo(()=>dispatchOrder?dispatchDecision(couriers,dispatchOrder):{selected:null,alternates:[],acceptanceSeconds:25},[couriers,dispatchOrder]);
 const ranked=decision.selected?[decision.selected,...decision.alternates]:[];
 const offeredId=order?.dispatchOffer?.courierId||null;const offered=ranked.find(x=>x.id===offeredId)||null;
 const offerTop=()=>{if(!order||!decision.selected)return;const expiresAt=new Date(Date.now()+decision.acceptanceSeconds*1000).toISOString();recordDispatchOffer(order.id,{courierId:decision.selected.id,courierName:decision.selected.name,score:decision.selected.dispatchScore,expiresAt});setSeconds(decision.acceptanceSeconds);setNotice("Oferta enviada a "+decision.selected.name+".")};
 const resolve=(outcome)=>{if(!order?.dispatchOffer)return;const courier={id:order.dispatchOffer.courierId,name:order.dispatchOffer.courierName};resolveDispatchOffer(order.id,outcome);if(outcome==="accepted"){assignCourierToOrder(order.id,{courierId:courier.id,courierName:courier.name});const current=loadCouriers().find(c=>c.id===courier.id);if(current)updateCourier(courier.id,{activeOrders:(current.activeOrders||0)+1,status:"En entrega"});setNotice("Pedido asignado a "+courier.name+".")}else setNotice(outcome==="rejected"?"El repartidor rechazó. Puedes ofrecer al siguiente candidato.":"La oferta venció. Puedes continuar con el siguiente candidato.")};
 useEffect(()=>{if(!order?.dispatchOffer?.expiresAt)return;const tick=()=>{const left=Math.max(0,Math.ceil((new Date(order.dispatchOffer.expiresAt).getTime()-Date.now())/1000));setSeconds(left);if(left===0)resolve("timeout")};tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[order?.id,order?.dispatchOffer?.expiresAt]);
 return <div className="dispatchPage"><header><div><b className="logo">Citri<span>Food</span></b><small>Asignación inteligente</small></div><a href="/operaciones">← Operaciones</a></header>
 <section className="dispatchHero"><div><small>PEDIDOS REALES DEL MVP PENDIENTES</small><h1>{order?.id||"Sin pedidos pendientes"}</h1><p>{order?order.restaurant+" → "+(order.address||"Cliente")+" · "+(Number(order.distanceKm)||0).toFixed(1)+" km":"Cuando un restaurante marque un pedido listo aparecerá aquí."}</p></div><div><b>{orders.length} por asignar</b><small>Solo compiten repartidores elegibles</small></div></section>
 {orders.length>1&&<label>Pedido <select value={selectedId||""} onChange={e=>setSelectedId(e.target.value)}>{orders.map(o=><option key={o.id} value={o.id}>{o.id} · {o.restaurant}</option>)}</select></label>}
 <div className="ranking"><h2>Ranking para este pedido</h2>{ranked.map((x,i)=><article className={i===0?"winner":""} key={x.id}><div className="rank">{i+1}</div><div><h3>{x.name}</h3><p>{x.distanceKm} km · ⭐ {x.rating} · {x.activeOrders||0} activos</p><small>Puntualidad {Math.round(x.onTimeRate*100)}% · Completados {Math.round(x.completionRate*100)}% · Cancelación {Math.round(x.cancelRate*100)}%</small></div><div className="score"><b>{x.dispatchScore}</b><small>puntos</small></div>{i===0&&<span className="recommended">Recomendado</span>}</article>)}</div>
 <section className="explain"><h2>Despacho</h2>{!order&&<p>No hay pedidos listos sin repartidor.</p>}{order&&!order.dispatchOffer&&<button disabled={!decision.selected} onClick={offerTop}>Ofrecer al mejor candidato · 25 s</button>}{order?.dispatchOffer&&<div className="offer">📲 Oferta a <b>{order.dispatchOffer.courierName}</b><small>{seconds} segundos restantes</small><div><button onClick={()=>resolve("rejected")}>Simular rechazo</button><button onClick={()=>resolve("accepted")}>Simular aceptación</button></div></div>}{notice&&<p>{notice}</p>}<p>La oferta y su resultado quedan guardados en el historial del pedido para auditoría.</p></section></div>;
}
