"use client";
import "./dispatch.css";
import {useMemo,useState} from "react";
import {rankCouriers} from "../../../lib/dispatch";
const seed=[
{id:"CF-R001",name:"Juan Pérez",distanceKm:1.0,online:true,available:true,endingShift:true,status:"Terminando jornada",activeOrders:2,documentsApproved:true,suspended:false,onTimeRate:.79,completionRate:.91,cancelRate:.12,rating:4.2,validIncidents:2},
{id:"CF-R002",name:"Pedro García",distanceKm:1.5,online:true,available:true,endingShift:false,status:"Disponible",activeOrders:1,documentsApproved:true,suspended:false,onTimeRate:.97,completionRate:.99,cancelRate:.01,rating:4.9,validIncidents:0},
{id:"CF-R003",name:"Luis Torres",distanceKm:2.2,online:true,available:true,endingShift:false,status:"Disponible",activeOrders:0,documentsApproved:true,suspended:false,onTimeRate:.94,completionRate:.97,cancelRate:.03,rating:4.8,validIncidents:0},
{id:"CF-R004",name:"Carlos Ruiz",distanceKm:.7,online:false,available:true,endingShift:false,status:"Desconectado",activeOrders:0,documentsApproved:true,suspended:false,onTimeRate:.98,completionRate:.99,cancelRate:0,rating:5,validIncidents:0}
];
export default function Dispatch(){const[couriers]=useState(seed);const[offered,setOffered]=useState(null);const ranked=useMemo(()=>rankCouriers(couriers),[couriers]);const excluded=couriers.filter(c=>!ranked.some(r=>r.id===c.id));return <div className="dispatchPage"><header><div><b className="logo">Citri<span>Food</span></b><small>Asignación inteligente</small></div><a href="/operaciones">← Operaciones</a></header><section className="dispatchHero"><div><small>PEDIDO NUEVO</small><h1>CF-1048</h1><p>🌮 Tacos El Centro → 📍 Cliente · 3.4 km</p></div><div><b>Pedido listo para asignar</b><small>Solo compiten repartidores realmente disponibles</small></div></section><div className="ranking"><h2>Ranking de repartidores elegibles</h2>{ranked.map((x,i)=><article className={i===0?"winner":""} key={x.id}><div className="rank">{i+1}</div><div><h3>{x.name}</h3><p>{x.distanceKm} km del restaurante · ⭐ {x.rating} · {x.activeOrders||0} pedido(s) activo(s)</p><small>Puntualidad {Math.round(x.onTimeRate*100)}% · Completados {Math.round(x.completionRate*100)}% · Cancelación {Math.round(x.cancelRate*100)}% · Incidencias {x.validIncidents}</small></div><div className="score"><b>{x.dispatchScore}</b><small>puntos</small></div>{i===0&&<span className="recommended">Recomendado</span>}</article>)}</div><section className="explain"><h2>Reglas activas</h2><p>Desconectados, suspendidos, documentos no aprobados y repartidores en <b>Terminando jornada</b> quedan fuera de cualquier pedido nuevo. Un repartidor puede acumular hasta 4 pedidos solo cuando sigue disponible.</p>{excluded.length>0&&<p><b>Fuera de esta asignación:</b> {excluded.map(x=>x.name+" ("+(x.status||"No elegible")+")").join(", ")}.</p>}{ranked[0]&&<p><b>{ranked[0].name}</b> encabeza el ranking con <b>{ranked[0].dispatchScore} puntos</b>. La decisión combina cercanía y desempeño.</p>}<button disabled={!ranked[0]} onClick={()=>setOffered(ranked[0])}>Ofrecer pedido al #1</button>{offered&&<div className="offer">📲 Pedido ofrecido a <b>{offered.name}</b><small>Tiene 25 segundos. Si no responde, pasa automáticamente al siguiente elegible.</small></div>}</section></div>;
}
