"use client";
import {useMemo,useState} from "react";
import "./order.css";
import {DELIVERY_RULES,canConfirmRestaurantArrival,canReceiveOrder,canStartCustomerHandoff,canEscalateAbsent,canReleaseAbsent,validateDeliveryPin} from "../../../lib/delivery-flow.js";
const clock=()=>new Date().toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit"});
export default function Pedido(){
 const[stage,setStage]=useState("to_restaurant"),[restaurantDistance,setRestaurantDistance]=useState(240),[customerDistance,setCustomerDistance]=useState(850),[gpsAccuracy]=useState(18),[restaurantReady,setRestaurantReady]=useState(false),[pin,setPin]=useState(""),[pinAttempts,setPinAttempts]=useState(0),[pinError,setPinError]=useState(""),[waitMinutes,setWaitMinutes]=useState(0),[messages,setMessages]=useState(0),[calls,setCalls]=useState(0),[supportOpened,setSupportOpened]=useState(false),[events,setEvents]=useState([{label:"Pedido aceptado",at:clock()}]);
 const arrived=canConfirmRestaurantArrival({distanceM:restaurantDistance,gpsAccuracyM:gpsAccuracy});
 const handoff=canStartCustomerHandoff({distanceM:customerDistance,pickedUp:stage==="to_customer"||stage==="handoff"});
 const addEvent=label=>setEvents(v=>[...v,{label,at:clock()}]);
 const markArrived=()=>{if(!arrived)return;setStage("at_restaurant");addEvent("Llegó al restaurante · aviso enviado a restaurante y cliente")};
 const receive=()=>{if(!canReceiveOrder({restaurantReady,restaurantArrivalVerified:stage==="at_restaurant"}))return;setStage("to_customer");addEvent("Pedido recibido · cliente avisado")};
 const openHandoff=()=>{if(!handoff)return;setStage("handoff");addEvent("Llegada al domicilio registrada")};
 const verify=()=>{const result=validateDeliveryPin("4827",pin,pinAttempts);setPinAttempts(result.attempts??pinAttempts);if(result.ok){setStage("delivered");addEvent("Entrega verificada con PIN")}else setPinError(result.locked?"PIN bloqueado. Contacta a Soporte.":"Código incorrecto.")};
 const escalate=()=>{if(canEscalateAbsent({minutesWaiting:waitMinutes,messages,calls})){setSupportOpened(true);addEvent("Caso enviado a Soporte: cliente no responde")}};
 const release=()=>{if(canReleaseAbsent({minutesWaiting:waitMinutes,messages,calls,supportCaseOpened:supportOpened})){setStage("absent");addEvent("Pedido liberado por cliente ausente")}};
 return <main className="orderRun"><header><a href="/repartidor">← Ruta</a><b>Citri<span>Food</span></b><small>CF-1052</small></header>
 {stage==="to_restaurant"&&<><section className="place"><small>RECOGER EN</small><h1>Taco Chuy</h1><p>Centro, Montemorelos</p><b>{restaurantDistance} m del restaurante · GPS ±{gpsAccuracy} m</b><button>🧭 Abrir navegación</button></section><div className="demoControls"><button onClick={()=>setRestaurantDistance(180)}>Simular 180 m</button><button onClick={()=>setRestaurantDistance(45)}>Simular 45 m</button></div><button className="primary" disabled={!arrived} onClick={markArrived}>{arrived?"Llegué al restaurante":"Acércate para registrar llegada"}</button><p className="audit">Se habilita dentro de {DELIVERY_RULES.restaurantArrivalRadiusM} m con ubicación GPS suficientemente precisa.</p></>}
 {stage==="at_restaurant"&&<><section className="place"><small>EN EL RESTAURANTE</small><h1>Esperando pedido</h1><p>El restaurante y el cliente ya fueron avisados de tu llegada.</p></section><label className="readyDemo"><input type="checkbox" checked={restaurantReady} onChange={e=>setRestaurantReady(e.target.checked)}/> Simular: restaurante marcó “Pedido listo”</label><button className="primary" disabled={!restaurantReady} onClick={receive}>{restaurantReady?"Recibí el pedido":"Esperando que el restaurante marque listo"}</button></>}
 {(stage==="to_customer"||stage==="handoff")&&<><section className="place"><small>ENTREGAR EN</small><h1>Cliente · Infonavit</h1><p>Infonavit, Montemorelos</p><b>{customerDistance} m del domicilio</b></section><div className="demoControls"><button onClick={()=>setCustomerDistance(95)}>Simular 95 m</button><button onClick={()=>setCustomerDistance(12)}>Simular 12 m</button></div>{customerDistance<=100&&stage==="to_customer"&&<p className="nearNotice">🔔 Cliente avisado: “Tu repartidor está por llegar.”</p>}{stage==="to_customer"&&<button className="primary" disabled={!handoff} onClick={openHandoff}>{handoff?"Entregar pedido":"Acércate al domicilio para entregar"}</button>}{stage==="handoff"&&<section className="handoff"><h2>Código de entrega</h2><p>Pide al cliente su PIN de 4 dígitos. No puedes cerrar el pedido sin validarlo.</p><input inputMode="numeric" maxLength={4} value={pin} onChange={e=>{setPin(e.target.value.replace(/\D/g,""));setPinError("")}} placeholder="••••"/><button className="primary" disabled={pin.length!==4||pinAttempts>=5} onClick={verify}>Verificar y entregar</button>{pinError&&<p className="pinError">{pinError}</p>}<hr/><h3>¿El cliente no responde?</h3><p>Espera registrada: <b>{waitMinutes} min</b></p><div className="demoControls"><button onClick={()=>{setMessages(v=>v+1);addEvent("Mensaje enviado al cliente")}}>💬 Mensaje ({messages})</button><button onClick={()=>{setCalls(v=>v+1);addEvent("Intento de llamada al cliente")}}>📞 Llamar ({calls})</button><button onClick={()=>setWaitMinutes(v=>Math.min(15,v+5))}>+5 min demo</button></div><button className="secondary" disabled={!canEscalateAbsent({minutesWaiting:waitMinutes,messages,calls})||supportOpened} onClick={escalate}>{supportOpened?"Soporte avisado":"Avisar a Soporte: cliente no responde"}</button><button className="danger" disabled={!canReleaseAbsent({minutesWaiting:waitMinutes,messages,calls,supportCaseOpened:supportOpened})} onClick={release}>Liberar pedido por cliente ausente</button><small>Requiere 15 min, caso abierto con Soporte y contacto mínimo: 1 mensaje o 2 llamadas.</small></section>}</>}
 {stage==="delivered"&&<section className="success"><h2>✓ Entrega completada</h2><p>PIN correcto. Pedido cerrado y registrado.</p><a href="/repartidor">Volver a mi ruta</a></section>}
 {stage==="absent"&&<section className="success"><h2>Pedido liberado</h2><p>Cliente ausente. El expediente conserva tiempos e intentos de contacto para Operaciones.</p><a href="/repartidor">Volver a mi ruta</a></section>}
 <section className="timeline"><h3>Registro de esta entrega</h3>{events.map((e,i)=><div className="done" key={i}><i>✓</i><span><b>{e.label}</b><small>{e.at}</small></span></div>)}</section>
 <p className="audit">Pantalla piloto: los botones de distancia y “pedido listo” simulan señales que después vendrán del GPS y del restaurante.</p></main>
}