import test from "node:test";
import assert from "node:assert/strict";
import {rankCouriers,rankForOrder,DISPATCH_CONFIG,recordOfferOutcome,courierScore} from "../lib/dispatch.js";
import {cents,settleCashOrder,cashOrderEligibility,applyDigitalOrderEarning,walletSummary,registerDeposit} from "../lib/wallet.js";
import {buildStops} from "../lib/route-planner.js";
import {csvCell,ordersToCsv} from "../lib/order-export.js";
import {orderMetrics} from "../lib/order-metrics.js";
import {addOrder,cancelOrder,canTransitionOrder,createOrder,clearMvp,getOrder,loadMvp,updateOrder} from "../lib/mvp-store.js";
import {addPromotion,initialPromotions,loadPromotions,promotionsFor,setPromotionActive,setPromotionSponsored,sponsoredPromotions} from "../lib/promotions.js";
const courier=(id,distanceKm,extra={})=>({id,distanceKm,online:true,available:true,documentsApproved:true,suspended:false,onTimeRate:.98,completionRate:.99,cancelRate:.01,rating:4.9,validIncidents:0,...extra});
test("ranking ignores offline and unverified couriers",()=>{const r=rankCouriers([courier("a",.5,{online:false}),courier("b",1),courier("c",.1,{documentsApproved:false})]);assert.deepEqual(r.map(x=>x.id),["b"])});
test("performance can outweigh small distance advantage",()=>{const r=rankCouriers([courier("near",1,{onTimeRate:.5,completionRate:.7,cancelRate:.25,rating:3.5,validIncidents:2}),courier("good",1.5)]);assert.equal(r[0].id,"good")});
test("unanswered offers receive a light penalty",()=>{const base=courier("a",1);const profile=recordOfferOutcome({offers:0},"timeout");assert.equal(profile.responseRate,0);assert.ok(courierScore({...base,...profile})<courierScore(base));assert.ok(courierScore(base)-courierScore({...base,...profile})<2)});
test("cash orders respect 800 peso exposure, card orders continue",()=>{const c=courier("a",1,{wallet:{amountToDepositCents:cents(780)}});const cash={paymentMethod:"cash",totalCents:cents(120),courierEarningCents:cents(35)};assert.equal(rankForOrder([c],cash).length,0);assert.equal(rankForOrder([c],{paymentMethod:"card"}).length,1);assert.equal(cashOrderEligibility({currentCashDebtCents:cents(700),orderCashTotalCents:cents(100),courierEarningCents:cents(35)}).eligible,true)});
test("cash settlement and digital earning reduce debt",()=>{const e=settleCashOrder({orderId:"CF-1",cashCollectedCents:cents(400),courierEarningCents:cents(35)});assert.equal(e.companyReceivableCents,cents(365));const s=walletSummary([e]);assert.equal(s.amountToDepositCents,cents(365));const digital=applyDigitalOrderEarning({orderId:"CF-2",earningCents:cents(40),currentCashDebtCents:s.amountToDepositCents});assert.equal(digital.resultingCashDebtCents,cents(325))});
test("deposit references are pending, not verified payments",()=>{assert.equal(registerDeposit({reference:"demo",amountCents:cents(100)}).status,"pending_verification")});
test("route never delivers before picking up",()=>{const stops=buildStops([{id:"A",restaurant:"Tacos",pickup:"Centro",destination:"Norte",pickupEta:5,deliveryEta:1},{id:"B",restaurant:"Pizza",pickup:"Centro",destination:"Sur",pickupEta:2,deliveryEta:3}]);for(const order of ["A","B"])assert.ok(stops.findIndex(s=>s.id===order+"-P")<stops.findIndex(s=>s.id===order+"-D"));assert.equal(DISPATCH_CONFIG.maxActiveOrders,4)});

test("order lifecycle blocks invalid jumps and terminal-state edits",()=>{assert.equal(canTransitionOrder("Nuevo","Entregado"),false);assert.equal(canTransitionOrder("Nuevo","Preparando"),true);assert.equal(canTransitionOrder("Entregado","Preparando"),false)});
test("customer order flows through restaurant, operations and courier in shared demo store",()=>{const values=new Map();const oldWindow=globalThis.window;const oldStorage=globalThis.localStorage;globalThis.window={dispatchEvent(){}};globalThis.localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};try{const order=addOrder({restaurant:"Burger House",customer:"Cliente",items:[{name:"Hamburguesa",qty:1,price:99}],total:128,address:"Centro",source:"customer-demo"});assert.equal(order.status,"Nuevo");assert.equal(order.statusHistory.length,1);assert.equal(loadMvp().orders.length,1);assert.equal(updateOrder(order.id,{status:"Entregado"}),null);assert.equal(getOrder(order.id).status,"Nuevo");assert.equal(updateOrder(order.id,{status:"Preparando"}).status,"Preparando");assert.equal(updateOrder(order.id,{status:"Listo"}).status,"Listo");assert.equal(updateOrder(order.id,{status:"En entrega",courier:"Juan Pérez (demo)"}).courier,"Juan Pérez (demo)");assert.equal(updateOrder(order.id,{status:"Entregado"}).status,"Entregado");assert.deepEqual(getOrder(order.id).statusHistory.map(e=>e.status),["Nuevo","Preparando","Listo","En entrega","Entregado"]);assert.equal(updateOrder(order.id,{status:"Preparando"}),null);assert.equal(getOrder(order.id).status,"Entregado");assert.equal(getOrder(order.id).statusHistory.length,5);clearMvp();assert.equal(loadMvp().orders.length,0)}finally{if(oldWindow===undefined)delete globalThis.window;else globalThis.window=oldWindow;if(oldStorage===undefined)delete globalThis.localStorage;else globalThis.localStorage=oldStorage}});

test("restaurant promotions appear by default, can be paused and added per restaurant",()=>{const values=new Map();const oldWindow=globalThis.window;const oldStorage=globalThis.localStorage;globalThis.window={dispatchEvent(){}};globalThis.localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};try{assert.equal(initialPromotions()["Tacos El Centro"][0].title,"2x1 en tacos de bistec");assert.equal(promotionsFor("Tacos El Centro").length,1);const original=promotionsFor("Tacos El Centro")[0];assert.equal(setPromotionActive("Tacos El Centro",original.id,false),true);assert.equal(promotionsFor("Tacos El Centro").length,0);const added=addPromotion("Pizza Norte",{title:"Pizza familiar",price:"199.50",description:"Solo de prueba"});assert.equal(added.price,199.5);assert.equal(added.sponsored,false);assert.equal(promotionsFor("Pizza Norte")[0].id,added.id);assert.equal(sponsoredPromotions().some(p=>p.id===added.id),false);assert.equal(setPromotionSponsored("Pizza Norte",added.id,true),true);assert.equal(sponsoredPromotions().some(p=>p.id===added.id),true);assert.equal(setPromotionActive("Pizza Norte",added.id,false),true);assert.equal(sponsoredPromotions().some(p=>p.id===added.id),false);assert.equal(loadPromotions()["Tacos El Centro"][0].active,false);assert.throws(()=>addPromotion("Pizza Norte",{title:"Sin precio",price:0}))}finally{if(oldWindow===undefined)delete globalThis.window;else globalThis.window=oldWindow;if(oldStorage===undefined)delete globalThis.localStorage;else globalThis.localStorage=oldStorage}});

test("customer cancellation is allowed only before restaurant acceptance",()=>{const values=new Map();const oldWindow=globalThis.window,oldStorage=globalThis.localStorage;globalThis.window={dispatchEvent(){}};globalThis.localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};try{const first=addOrder({restaurant:"Tacos El Centro",total:100});assert.equal(cancelOrder(first.id).status,"Cancelado");assert.equal(getOrder(first.id).statusHistory.at(-1).status,"Cancelado");assert.equal(cancelOrder(first.id),null);assert.equal(updateOrder(first.id,{status:"Preparando"}),null);const second=addOrder({restaurant:"Pizza Norte",total:200});assert.equal(updateOrder(second.id,{status:"Preparando"}).status,"Preparando");assert.equal(cancelOrder(second.id),null);assert.equal(canTransitionOrder("Cancelado","Entregado"),false)}finally{if(oldWindow===undefined)delete globalThis.window;else globalThis.window=oldWindow;if(oldStorage===undefined)delete globalThis.localStorage;else globalThis.localStorage=oldStorage}});

test("CSV export quotes user fields and prevents spreadsheet formula execution",()=>{assert.equal(csvCell('Burger "House"'),'"Burger ""House"""');assert.equal(csvCell("=HYPERLINK(\"bad\")"),'"\'=HYPERLINK(""bad"")"');const csv=ordersToCsv([{id:"CF-1",restaurant:"Tacos, El Centro",customer:"=1+1",address:"Centro",status:"Nuevo",paymentMethod:"Efectivo (simulado)",total:120,deliveryFee:25}]);assert.ok(csv.charCodeAt(0)===0xFEFF);assert.ok(csv.includes('"Tacos, El Centro"'));assert.ok(csv.includes('"\'=1+1"'));assert.ok(csv.includes('"120.00"'));assert.ok(csv.includes('"25.00"'))});

test("restaurant reports exclude illustrative cards and never treat unfulfilled orders as delivered value",()=>{const metrics=orderMetrics([{id:"CF-DEMO-1",restaurant:"Tacos",status:"Entregado",total:9999},{id:"CF-1",restaurant:"Tacos",status:"Entregado",total:120.25},{id:"CF-2",restaurant:"Tacos",status:"Cancelado",total:300},{id:"CF-3",restaurant:"Pizza",status:"Preparando",total:200},{id:"CF-4",restaurant:"Pizza",status:"Rechazado",total:150}]);assert.equal(metrics.total,4);assert.equal(metrics.delivered,1);assert.equal(metrics.active,1);assert.equal(metrics.cancelled,1);assert.equal(metrics.rejected,1);assert.equal(metrics.deliveredTotalCents,12025);assert.equal(metrics.restaurants.find(x=>x.restaurant==="Tacos").total,2);assert.equal(orderMetrics([]).deliveredTotalCents,0)});

test("date and restaurant report filters",()=>{const orders=[{id:"CF-A",restaurant:"Tacos",createdAt:"2026-09-19T23:50:00Z",status:"Entregado",total:100},{id:"CF-B",restaurant:"Tacos",createdAt:"2026-09-20T01:00:00Z",status:"Entregado",total:200},{id:"CF-C",restaurant:"Pizza",createdAt:"2026-09-20T02:00:00Z",status:"Entregado",total:300},{id:"CF-D",restaurant:"Tacos",createdAt:"2026-09-20T04:00:00Z",status:"Cancelado",total:400}];const report=orderMetrics(orders,{from:"2026-09-20",to:"2026-09-20",restaurant:"Tacos"});assert.equal(report.total,2);assert.equal(report.delivered,1);assert.equal(report.cancelled,1);assert.equal(report.deliveredTotalCents,20000);assert.equal(orderMetrics(orders,{to:"2026-09-19"}).total,1)});

test("demo order identity and initial history cannot be overridden by checkout data",()=>{const order=createOrder({id:"CF-DEMO-1",createdAt:"2000-01-01",status:"Entregado",statusHistory:[{status:"Entregado"}],restaurant:"Pizza Norte"});assert.ok(order.id.startsWith("CF-"));assert.notEqual(order.id,"CF-DEMO-1");assert.notEqual(order.createdAt,"2000-01-01");assert.equal(order.status,"Nuevo");assert.deepEqual(order.statusHistory.map(e=>e.status),["Nuevo"])});

test("checkout recipient and delivery instructions persist through order creation",()=>{const order=createOrder({restaurant:"Burger House",customer:"Cliente de prueba",address:"Centro",deliveryNotes:"Portón azul, tocar timbre",paymentMethod:"Efectivo (simulado)",total:129});assert.equal(order.customer,"Cliente de prueba");assert.equal(order.deliveryNotes,"Portón azul, tocar timbre");assert.equal(order.address,"Centro");assert.equal(order.status,"Nuevo")});
