import "./operations.css";
"use client";
import {useState} from "react";
const initial=[
{id:"CF-R001",name:"Juan Pérez",phone:"826 000 1122",status:"En entrega",orders:14,accept:"96%",zone:"Centro",vehicle:"Moto",docs:"Verificado"},
{id:"CF-R002",name:"Luis García",phone:"826 000 2233",status:"Disponible",orders:9,accept:"91%",zone:"Matamoros",vehicle:"Auto",docs:"Verificado"},
{id:"CF-R003",name:"Carlos Ruiz",phone:"826 000 3344",status:"Desconectado",orders:6,accept:"88%",zone:"Morelos",vehicle:"Moto",docs:"Pendiente"},
{id:"CF-R004",name:"Ana Torres",phone:"826 000 4455",status:"Disponible",orders:11,accept:"98%",zone:"Centro",vehicle:"Moto",docs:"Verificado"}
];
export default function Operations(){const[drivers,setDrivers]=useState(initial);const[filter,setFilter]=useState("Todos");const[selected,setSelected]=useState(null);const visible=filter==="Todos"?drivers:drivers.filter(x=>x.status===filter);const counts={online:drivers.filter(x=>x.status!=="Desconectado").length,busy:drivers.filter(x=>x.status==="En entrega").length,free:drivers.filter(x=>x.status==="Disponible").length,off:drivers.filter(x=>x.status==="Desconectado").length};return <div className="ops"><aside><b className="brand">CitriFood</b><span>Centro de Operaciones</span><a className="active">📊 Resumen</a><a href="/repartidor">🛵 Repartidores</a><a href="/operaciones/asignacion">🧾 Asignación</a><a href="/restaurante">🏪 Restaurantes</a><a>👥 Solicitudes</a><a>⚠️ Incidencias</a></aside><main className="opsmain"><div className="ophead"><div><h1>Operación en vivo</h1><p>Monitoreo de repartidores y pedidos</p></div><button>+ Alta de repartidor</button></div><section className="stats"><article><small>Conectados</small><b>{counts.online}</b></article><article><small>Entregando</small><b>{counts.busy}</b></article><article><small>Disponibles</small><b>{counts.free}</b></article><article><small>Desconectados</small><b>{counts.off}</b></article></section><section className="mapmock"><div className="maplabel"><b>Mapa operativo</b><small>Vista preliminar · ubicación en tiempo real</small></div><i className="pin p1">🛵</i><i className="pin p2">🛵</i><i className="pin p3">📦</i></section><section className="driverPanel"><div className="panelhead"><h2>Repartidores</h2><div>{["Todos","Disponible","En entrega","Desconectado"].map(x=><button className={filter===x?"on":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="driverTable"><div className="tr th"><span>Repartidor</span><span>Estado</span><span>Zona</span><span>Pedidos</span><span>Aceptación</span><span></span></div>{visible.map(x=><button className="tr" onClick={()=>setSelected(x)} key={x.id}><span><b>{x.name}</b><small>{x.id}</small></span><span className={"status "+x.status.replace(" ","").toLowerCase()}>{x.status}</span><span>{x.zone}</span><span>{x.orders}</span><span>{x.accept}</span><span>›</span></button>)}</div></section>{selected&&<div className="modalbg" onClick={()=>setSelected(null)}><div className="driverModal" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setSelected(null)}>×</button><div className="avatar">👤</div><h2>{selected.name}</h2><p>{selected.id} · {selected.status}</p><hr/><p><b>Teléfono:</b> {selected.phone}</p><p><b>Vehículo:</b> {selected.vehicle}</p><p><b>Documentos:</b> {selected.docs}</p><p><b>Pedidos hoy:</b> {selected.orders}</p><p><b>Aceptación:</b> {selected.accept}</p><div className="actions"><button>Ver ubicación</button><button>Ver expediente</button></div></div></div>}</main></div>}