"use client";
import {useEffect,useState} from "react";
import {cancelAcceptedByRestaurant,getRestaurantPenaltyBalance,loadMvp,subscribeOrders,updateOrder} from "../../lib/mvp-store.js";
import "./restaurant.css";
import {addPromotion,loadPromotions,setPromotionActive,setPromotionSponsored,subscribePromotions} from "../../lib/promotions.js";
const names=["Tacos El Centro","Burger House","Pizza Norte","Sushi Mty"];
const seed=[{id:"CF-DEMO-1",restaurant:"Tacos El Centro",customer:"María (ejemplo)",items:"3 tacos + refresco",total:245,status:"Nuevo",demo:true},{id:"CF-DEMO-2",restaurant:"Tacos El Centro",customer:"José (ejemplo)",items:"1 pirata + papa",total:210,status:"Preparando",demo:true}];
export default function Restaurante(){
 const[restaurant,setRestaurant]=useState(names[0]);
 const[actual,setActual]=useState([]);\n const[notice,setNotice]=useState("");
 const[examples,setExamples]=useState(seed);
 const[promotions,setPromotions]=useState({});const[title,setTitle]=useState("");const[description,setDescription]=useState("");const[price,setPrice]=useState("");const[promoError,setPromoError]=useState("");
 useEffect(()=>{const refresh=()=>setActual(loadMvp().orders);refresh();return subscribeOrders(refresh)},[]);
 useEffect(()=>{const refresh=()=>setPromotions(loadPromotions());refresh();return subscribePromotions(refresh)},[]);
 const createPromo=e=>{e.preventDefault();try{addPromotion(restaurant,{title,description,price,emoji:"🍽️"});setTitle("");setDescription("");setPrice("");setPromoError("")}catch{setPromoError("Escribe un nombre y un precio válido mayor a cero.")}};
 const orders=[...actual.filter(o=>o.restaurant===restaurant),...examples.filter(o=>o.restaurant===restaurant)];\n const penaltyBalance=getRestaurantPenaltyBalance(restaurant);\n const paidSales=orders.filter(o=>!o.id.startsWith("CF-DEMO-")&&!["Nuevo","Rechazado","Cancelado"].includes(o.status)).reduce((s,o)=>s+(Number(o.total)||0),0);\n const cancelAccepted=o=>{if(o.id.startsWith("CF-DEMO-")){setExamples(v=>v.map(x=>x.id===o.id?{...x,status:"Rechazado"}:x));setNotice("Ejemplo: cancelación después de aceptar · penalización $20.");return}const updated=cancelAcceptedByRestaurant(o.id,"Producto agotado");if(updated)setNotice("Pedido cancelado. Se solicitó el reembolso al cliente y se cargó una penalización de $20 a la próxima venta.");};
 const change=(o,status)=>{if(o.id.startsWith("CF-DEMO-"))setExamples(v=>v.map(x=>x.id===o.id?{...x,status}:x));else updateOrder(o.id,{status})};
 return <main className="restaurantDash"><header><div><b>Citri<span>Food</span></b><small>Portal del restaurante · Demostración</small></div><a href="/acceso">Cambiar perfil</a></header>
 <label className="restaurantPicker">Restaurante <select value={restaurant} onChange={e=>setRestaurant(e.target.value)}>{names.map(name=><option key={name} value={name}>{name}</option>)}</select></label>
 <section className="restaurantStats"><article><small>Nuevos</small><b>{orders.filter(x=>x.status==="Nuevo").length}</b></article><article><small>Ventas procesadas (demo)</small><b>$ {paidSales.toFixed(2)}</b></article><article><small>Penalizaciones pendientes</small><b>$ {penaltyBalance.toFixed(2)}</b></article></section>{notice&&<div className="restaurantNotice" role="status">{notice}</div>}
 <section className="promoManager"><h2>🔥 Promociones de {restaurant}</h2><p>Las promociones activas aparecen primero en el menú. El espacio patrocinado de portada se simula con un interruptor independiente: no genera cobros ni contrata publicidad. Solo se comparte entre pestañas de este navegador.</p><div className="promoManagerList">{(promotions[restaurant]||[]).length===0?<p>Sin promociones registradas.</p>:(promotions[restaurant]||[]).map(p=><article key={p.id}><div><b>{p.title}</b><small>{p.description} · $ {p.price} · {p.active===false?"Pausada":"Activa"}</small></div><div className="promoActions"><label><input type="checkbox" checked={p.sponsored===true} onChange={e=>setPromotionSponsored(restaurant,p.id,e.target.checked)}/> Patrocinada (demo)</label><button type="button" onClick={()=>setPromotionActive(restaurant,p.id,p.active===false)}>{p.active===false?"Activar":"Pausar"}</button></div></article>)}</div><form onSubmit={createPromo}><h3>Nueva promoción</h3><label>Nombre<input value={title} maxLength={80} onChange={e=>setTitle(e.target.value)} placeholder="Ej. 2 hamburguesas por $150" required/></label><label>Descripción<input value={description} maxLength={180} onChange={e=>setDescription(e.target.value)} placeholder="¿Qué incluye?"/></label><label>Precio en MXN<input value={price} type="number" min="0.01" step="0.01" onChange={e=>setPrice(e.target.value)} required/></label>{promoError&&<p role="alert">{promoError}</p>}<button className="main" type="submit">+ Crear promoción de prueba</button></form></section>
 <h1>Pedidos de {restaurant}</h1><p>Pedidos creados en este navegador. Los identificados como ejemplo no son pedidos de clientes.</p>
 <section className="restaurantOrders">{orders.length===0&&<p>Sin pedidos por ahora. Puedes crear uno desde la pantalla del cliente.</p>}{orders.map(o=><article key={o.id}><div><small>{o.id}{o.id.startsWith("CF-DEMO-")?" · EJEMPLO":""}</small><h2>{o.customer}</h2><p>{Array.isArray(o.items)?o.items.map(x=>x.qty+" × "+x.name).join(", "):o.items}</p>{!o.id.startsWith("CF-DEMO-")&&<div className="restaurantDeliveryInfo"><p><b>📍 Dirección:</b> {o.address||"No registrada"}</p>{o.deliveryNotes&&<p><b>📝 Indicaciones:</b> {o.deliveryNotes}</p>}<p><b>Pago:</b> {o.paymentMethod||"No indicado"}</p></div>}<b>$ {o.total}</b>{!o.id.startsWith("CF-DEMO-")&&o.refundStatus&&<small>💳 {o.refundStatus}</small>}{!o.id.startsWith("CF-DEMO-")&&(o.restaurantPenalties||[]).map(p=><small key={p.id}>⚠️ Penalización ${p.amount}: {p.reason}</small>)}</div><span className="restaurantStatus">{o.status}</span><div className="restaurantActions">{o.status==="Nuevo"&&<><button onClick={()=>change(o,"Rechazado")}>Rechazar</button><button className="main" onClick={()=>change(o,"Preparando")}>Aceptar pedido</button></>}{o.status==="Preparando"&&<><button onClick={()=>cancelAccepted(o)}>Cancelar · producto agotado</button><button className="main" onClick={()=>change(o,"Listo")}>Marcar listo</button></>}{o.status==="Listo"&&<button className="main" onClick={()=>change(o,"Esperando repartidor")}>Entregar a repartidor</button>}</div></article>)}</section><a className="backOps" href="/operaciones">← Centro de operaciones</a></main>
}