"use client";
import {useMemo,useState} from "react";
const restaurants=[
{id:1,name:"Tacos El Centro",cat:"Tacos",eta:"20–30 min",rating:4.8,delivery:25,emoji:"🌮",ad:true,promo:"2x1 en tacos de bistec",menu:[["Tacos de bistec",75,"🌮"],["Pirata",85,"🫓"],["Papa asada",95,"🥔"]]},
{id:2,name:"Burger House",cat:"Hamburguesas",eta:"25–35 min",rating:4.7,delivery:29,emoji:"🍔",ad:true,promo:"Combo Citri $129",menu:[["Hamburguesa clásica",99,"🍔"],["Papas",49,"🍟"],["Combo Citri",129,"🥤"]]},
{id:3,name:"Pizza Norte",cat:"Pizza",eta:"30–40 min",rating:4.6,delivery:19,emoji:"🍕",menu:[["Pepperoni",149,"🍕"],["Suprema",179,"🍕"]]},
{id:4,name:"Sushi Mty",cat:"Sushi",eta:"35–45 min",rating:4.9,delivery:35,emoji:"🍣",menu:[["California roll",115,"🍣"],["Tempura roll",135,"🍱"]]}
];
export default function Home(){
 const[q,setQ]=useState(""); const[selected,setSelected]=useState(null); const[cart,setCart]=useState([]); const[showCart,setShowCart]=useState(false); const[checkout,setCheckout]=useState(false); const[ordered,setOrdered]=useState(false); const[address,setAddress]=useState(""); const[payment,setPayment]=useState("Efectivo"); const[checkout,setCheckout]=useState(false); const[ordered,setOrdered]=useState(false); const[address,setAddress]=useState(""); const[payment,setPayment]=useState("Efectivo");
 const shown=useMemo(()=>restaurants.filter(x=>(x.name+" "+x.cat).toLowerCase().includes(q.toLowerCase())),[q]);
 const add=(name,price,emoji)=>setCart(items=>{const found=items.find(x=>x.name===name);return found?items.map(x=>x.name===name?{...x,qty:x.qty+1}:x):[...items,{name,price,emoji,qty:1}]});
 const change=(name,d)=>setCart(items=>items.map(x=>x.name===name?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0));
 const qty=cart.reduce((s,x)=>s+x.qty,0); const subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0); const delivery=selected?.delivery||25; const total=subtotal+(subtotal?delivery:0);
 if(ordered)return <main><header><b className="logo">Citri<span>Food</span></b></header><section className="orderDone"><div className="success">✓</div><h1>¡Pedido confirmado!</h1><p>Tu restaurante ya recibió el pedido.</p><div className="tracking"><div className="track active">✓<span>Pedido confirmado</span></div><div className="track active">🍳<span>Preparando tu comida</span></div><div className="track">🛵<span>Repartidor por asignar</span></div><div className="track">🏠<span>Entrega</span></div></div><div className="orderInfo"><p><b>Entrega en</b><br/>{address}</p><p><b>Forma de pago</b><br/>{payment}</p><p><b>Total</b><br/>$ {total}</p></div><button className="primary" onClick={()=>{setOrdered(false);setCheckout(false);setShowCart(false);setCart([]);setSelected(null)}}>Volver al inicio</button></section></main>;
 if(checkout)return <main><header><button className="back" onClick={()=>setCheckout(false)}>←</button><b className="logo">Citri<span>Food</span></b><span/></header><section className="checkout"><h1>Finalizar pedido</h1><label className="field"><b>📍 Dirección de entrega</b><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Calle, número, colonia y referencias"/></label><div className="field"><b>💳 Forma de pago</b><div className="payments">{["Efectivo","Tarjeta","Pago al recibir"].map(x=><button className={payment===x?"chosen":""} key={x} onClick={()=>setPayment(x)}>{x}</button>)}</div></div><div className="totals"><p>Subtotal <b>$ {subtotal}</b></p><p>Envío <b>$ {delivery}</b></p><h2>Total <b>$ {total}</b></h2></div><button className="primary" disabled={!address.trim()} onClick={()=>setOrdered(true)}>Confirmar pedido · $ {total}</button>{!address.trim()&&<small className="hint">Escribe la dirección para continuar.</small>}</section></main>;
 if(ordered)return <main><header><b className="logo">Citri<span>Food</span></b></header><section className="tracking"><div className="success">✓</div><h1>¡Pedido confirmado!</h1><p>Pedido #CF-1001 · Llegada estimada 25–35 min</p><div className="trackSteps"><div className="done"><b>1</b><span><strong>Pedido recibido</strong><small>El restaurante recibió tu pedido</small></span></div><div className="active"><b>2</b><span><strong>Preparando tu comida</strong><small>Te avisaremos cuando esté lista</small></span></div><div><b>3</b><span><strong>Repartidor en camino</strong><small>Pendiente</small></span></div><div><b>4</b><span><strong>Entregado</strong><small>Pendiente</small></span></div></div><button className="primary" onClick={()=>{setOrdered(false);setCart([]);setSelected(null)}}>Volver al inicio</button></section></main>;
 if(checkout)return <main><header><button className="back" onClick={()=>setCheckout(false)}>←</button><b className="logo">Citri<span>Food</span></b><span/></header><section className="checkout"><h1>Finalizar pedido</h1><label>Dirección de entrega</label><textarea value={address} onChange={e=>setAddress(e.target.value)} placeholder="Calle, número, colonia y referencias"/><h2>Forma de pago</h2><div className="payOptions">{["Efectivo","Tarjeta al recibir","Tarjeta en app"].map(x=><button className={payment===x?"selectedPay":""} onClick={()=>setPayment(x)} key={x}>{x==="Efectivo"?"💵":"💳"} {x}</button>)}</div><div className="totals"><p>Productos <b>$ {subtotal}</b></p><p>Envío <b>$ {delivery}</b></p><h2>Total <b>$ {total}</b></h2></div><button className="primary" disabled={!address.trim()} onClick={()=>setOrdered(true)}>Confirmar pedido · $ {total}</button>{!address.trim()&&<small className="hint">Agrega una dirección para continuar</small>}</section></main>;
 if(showCart)return <main><header><button className="back" onClick={()=>setShowCart(false)}>←</button><b className="logo">Citri<span>Food</span></b><span/></header><section className="checkout"><h1>Tu pedido</h1>{cart.length===0?<div className="empty">🛒<h2>Tu carrito está vacío</h2><button className="primary" onClick={()=>setShowCart(false)}>Buscar comida</button></div>:<><div className="cartList">{cart.map(x=><div className="cartrow" key={x.name}><div><b>{x.emoji} {x.name}</b><small>$ {x.price} c/u</small></div><div className="stepper"><button onClick={()=>change(x.name,-1)}>−</button><span>{x.qty}</span><button onClick={()=>change(x.name,1)}>+</button></div><strong>$ {x.price*x.qty}</strong></div>)}</div><div className="totals"><p>Subtotal <b>$ {subtotal}</b></p><p>Envío <b>$ {delivery}</b></p><h2>Total <b>$ {total}</b></h2></div><button className="primary" onClick={()=>setCheckout(true)}>Continuar pedido</button></>}</section></main>;
 if(selected)return <main><header><button className="back" onClick={()=>setSelected(null)}>←</button><b className="logo">Citri<span>Food</span></b><button className="cart" onClick={()=>setShowCart(true)}>🛒 {qty}</button></header><section className="restaurantHero"><div>{selected.emoji}</div><h1>{selected.name}</h1><p>⭐ {selected.rating} · {selected.eta} · Envío $ {selected.delivery}</p>{selected.ad&&<strong>🔥 {selected.promo}</strong>}</section><h2>Menú</h2><div className="menu">{selected.menu.map(([name,price,emoji])=><article key={name}><div><h3>{name}</h3><p>Preparado al momento</p><b>$ {price}</b></div><div className="menuEmoji">{emoji}</div><button onClick={()=>add(name,price,emoji)}>+ Agregar</button></article>)}</div>{qty>0&&<button className="floatingCart" onClick={()=>setShowCart(true)}>Ver carrito · {qty} · $ {total}</button>}</main>;
 return <main><header><div><b className="logo">Citri<span>Food</span></b><small>Entrega local</small></div><button className="cart" onClick={()=>setShowCart(true)}>🛒 {qty}</button></header><section className="hero"><p className="eyebrow">📍 Cerca de ti</p><h1>¿Qué se te antoja hoy?</h1><p>Comida de tus restaurantes favoritos, directo a tu puerta.</p><input value={q} onChange={e=>setQ(e.target.value)} placeholder="🔎 Buscar comida o restaurante"/></section><section><h2>Promociones para ti</h2><div className="promos">{restaurants.filter(x=>x.ad).map(x=><article className="promo" key={x.name}><span>Patrocinado</span><div className="food">{x.emoji}</div><h3>{x.promo}</h3><p>{x.name}</p><button onClick={()=>setSelected(x)}>Ver promoción</button></article>)}</div></section><section><div className="sectionTitle"><h2>Restaurantes</h2><span>{shown.length} disponibles</span></div><div className="grid">{shown.map(x=><article className="card" key={x.name}><div className="cover">{x.emoji}{x.ad&&<i>Promoción</i>}</div><div className="pad"><h3>{x.name}</h3><p>{x.cat} · ⭐ {x.rating}</p><p>🛵 {x.eta} · Envío $ {x.delivery}</p><button onClick={()=>setSelected(x)}>Ver menú</button></div></article>)}</div></section><nav><b>🏠<small>Inicio</small></b><b>🔎<small>Buscar</small></b><b>🧾<small>Pedidos</small></b><b>👤<small>Cuenta</small></b></nav></main>
}