"use client";
import {useEffect,useMemo,useState} from "react";
import {addOrder,getOrder,subscribeOrders} from "../lib/mvp-store.js";
import {loadPromotions,subscribePromotions} from "../lib/promotions.js";
const restaurants=[
{id:1,name:"Tacos El Centro",cat:"Tacos",eta:"20–30 min",rating:4.8,delivery:25,emoji:"🌮",ad:true,promo:"2x1 en tacos de bistec",promotions:[{id:"tacos-2x1",title:"2x1 en tacos de bistec",description:"Llévate dos tacos por el precio de uno.",name:"Promo 2x1 · Tacos de bistec",price:75,emoji:"🌮",label:"2 × $75"}],menu:[["Tacos de bistec",75,"🌮"],["Pirata",85,"🫓"],["Papa asada",95,"🥔"]]},
{id:2,name:"Burger House",cat:"Hamburguesas",eta:"25–35 min",rating:4.7,delivery:29,emoji:"🍔",ad:true,promo:"Combo Citri $129",promotions:[{id:"combo-citri",title:"Combo Citri",description:"Combo especial de Burger House.",name:"Combo Citri",price:129,emoji:"🍔",label:"$129"}],menu:[["Hamburguesa clásica",99,"🍔"],["Papas",49,"🍟"],["Combo Citri",129,"🥤"]]},
{id:3,name:"Pizza Norte",cat:"Pizza",eta:"30–40 min",rating:4.6,delivery:19,emoji:"🍕",menu:[["Pepperoni",149,"🍕"],["Suprema",179,"🍕"]]},
{id:4,name:"Sushi Mty",cat:"Sushi",eta:"35–45 min",rating:4.9,delivery:35,emoji:"🍣",menu:[["California roll",115,"🍣"],["Tempura roll",135,"🍱"]]}
];
export default function Home(){
 const[q,setQ]=useState(""); const[selected,setSelected]=useState(null); const[cart,setCart]=useState([]); const[showCart,setShowCart]=useState(false); const[checkout,setCheckout]=useState(false); const[ordered,setOrdered]=useState(false); const[address,setAddress]=useState(""); const[payment,setPayment]=useState("Efectivo (simulado)"); const[orderId,setOrderId]=useState(null); const[orderStatus,setOrderStatus]=useState("Nuevo"); const[myOrders,setMyOrders]=useState(false); const[history,setHistory]=useState([]); const[trackedTotal,setTrackedTotal]=useState(null); const[trackedOrder,setTrackedOrder]=useState(null); const[promotions,setPromotions]=useState({});
 useEffect(()=>{const refresh=()=>setPromotions(loadPromotions());refresh();return subscribePromotions(refresh)},[]);
 useEffect(()=>{const refresh=()=>{if(orderId){const current=getOrder(orderId);setOrderStatus(current?.status||"Nuevo");setTrackedOrder(current)}if(typeof window!=="undefined"){const ids=JSON.parse(localStorage.getItem("citrifood_customer_orders")||"[]");setHistory(ids.map(getOrder).filter(Boolean))}};refresh();return subscribeOrders(refresh)},[orderId]);
 const confirmOrder=()=>{const order=addOrder({restaurant:selected.name,customer:"Cliente",items:cart.map(x=>({name:x.name,qty:x.qty,price:x.price})),total,address,paymentMethod:payment,deliveryFee:delivery,source:"customer-demo"});setOrderId(order.id);setOrderStatus(order.status);setTrackedTotal(order.total);setTrackedOrder(order);setOrdered(true);if(typeof window!=="undefined"){const ids=JSON.parse(localStorage.getItem("citrifood_customer_orders")||"[]");localStorage.setItem("citrifood_customer_orders",JSON.stringify([order.id,...ids].slice(0,30)))}};
 const selectedPromos=selected?(promotions[selected.name]||[]).filter(p=>p.active!==false):[];
 const shown=useMemo(()=>restaurants.filter(x=>(x.name+" "+x.cat).toLowerCase().includes(q.toLowerCase())),[q]);
 const add=(name,price,emoji)=>setCart(items=>{const found=items.find(x=>x.name===name);return found?items.map(x=>x.name===name?{...x,qty:x.qty+1}:x):[...items,{name,price,emoji,qty:1}]});
 const change=(name,d)=>setCart(items=>items.map(x=>x.name===name?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0));
 const openRestaurant=(restaurant)=>{if(selected?.id!==restaurant.id&&cart.length){setCart([]);setShowCart(false);setCheckout(false)}setSelected(restaurant)};
 const qty=cart.reduce((s,x)=>s+x.qty,0); const subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0); const delivery=selected?.delivery||25; const total=subtotal+(subtotal?delivery:0);
 if(myOrders)return <main><header><button className="back" onClick={()=>setMyOrders(false)}>←</button><b className="logo">Citri<span>Food</span></b></header><section className="checkout"><h1>Mis pedidos de prueba</h1><p>Solo pedidos creados en este navegador. No se sincronizan entre dispositivos.</p>{history.length===0?<p>Aún no tienes pedidos.</p>:history.map(o=><article className="historyOrder" key={o.id}><b>{o.id} · {o.restaurant}</b><p>{o.status}</p><small>{o.address} · $ {o.total}</small><button onClick={()=>{setOrderId(o.id);setOrderStatus(o.status);setAddress(o.address);setPayment(o.paymentMethod);setTrackedTotal(o.total);setTrackedOrder(o);setOrdered(true);setMyOrders(false)}}>Ver seguimiento</button></article>)}</section></main>;
 if(ordered)return <main><div className="devAccess"><a href="/repartidor">🛵 Repartidor</a><a href="/restaurante">🏪 Restaurante</a><a href="/operaciones">🖥️ Operaciones</a></div><header><b className="logo">Citri<span>Food</span></b></header><section className="tracking"><div className="success">✓</div><h1>¡Pedido confirmado!</h1><p>Pedido #{orderId} · Seguimiento de demostración</p><div className="trackSteps">{orderStatus==="Rechazado"?<div className="rejectedOrder"><b>!</b><span><strong>Pedido rechazado por el restaurante</strong><small>Este pedido de demostración no continuará.</small></span></div>:[["Nuevo","Pedido recibido"],["Preparando","Restaurante preparando"],["Listo","Comida lista"],["Esperando repartidor","Esperando repartidor"],["En entrega","Repartidor en camino"],["Entregado","Pedido entregado"]].map(([status,label],i,steps)=><div className={steps.findIndex(x=>x[0]===orderStatus)>i?"done":orderStatus===status?"active":""} key={status}><b>{i+1}</b><span><strong>{label}</strong><small>{orderStatus===status?"Estado actual":" "}</small></span></div>)}</div><div className="orderInfo">{trackedOrder?.statusHistory?.length>0&&<details className="orderAudit"><summary>Ver historial del pedido</summary>{trackedOrder.statusHistory.map((event,i)=><p key={i}><b>{event.status}</b> · {new Date(event.at).toLocaleString("es-MX")}</p>)}</details>}<p><b>Entrega en</b><br/>{address}</p><p><b>Forma de pago</b><br/>{payment}</p><p><b>Total</b><br/>$ {trackedTotal??total}</p></div><button className="primary" onClick={()=>{setOrdered(false);setCheckout(false);setShowCart(false);setCart([]);setSelected(null);setOrderId(null);setTrackedTotal(null);setTrackedOrder(null)}}>Volver al inicio</button></section></main>;
 if(checkout)return <main><header><button className="back" onClick={()=>setCheckout(false)}>←</button><b className="logo">Citri<span>Food</span></b><span/></header><section className="checkout"><h1>Finalizar pedido</h1><p>Modo de prueba: no se cobran tarjetas ni se solicitan datos bancarios.</p><label className="field"><b>📍 Dirección de entrega</b><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Calle, número, colonia y referencias"/></label><div className="field"><b>💳 Forma de pago</b><div className="payments">{["Efectivo (simulado)","Tarjeta (simulada)"].map(x=><button className={payment===x?"chosen":""} key={x} onClick={()=>setPayment(x)}>{x}</button>)}</div></div><div className="totals"><p>Subtotal <b>$ {subtotal}</b></p><p>Envío <b>$ {delivery}</b></p><h2>Total <b>$ {total}</b></h2></div><button className="primary" disabled={!address.trim()||!selected||!cart.length} onClick={confirmOrder}>Confirmar pedido · $ {total}</button>{!address.trim()&&<small className="hint">Escribe la dirección para continuar.</small>}</section></main>;
 if(showCart)return <main><header><button className="back" onClick={()=>setShowCart(false)}>←</button><b className="logo">Citri<span>Food</span></b><span/></header><section className="checkout"><h1>Tu pedido</h1>{cart.length===0?<div className="empty">🛒<h2>Tu carrito está vacío</h2><button className="primary" onClick={()=>setShowCart(false)}>Buscar comida</button></div>:<><div className="cartList">{cart.map(x=><div className="cartrow" key={x.name}><div><b>{x.emoji} {x.name}</b><small>$ {x.price} c/u</small></div><div className="stepper"><button onClick={()=>change(x.name,-1)}>−</button><span>{x.qty}</span><button onClick={()=>change(x.name,1)}>+</button></div><strong>$ {x.price*x.qty}</strong></div>)}</div><div className="totals"><p>Subtotal <b>$ {subtotal}</b></p><p>Envío <b>$ {delivery}</b></p><h2>Total <b>$ {total}</b></h2></div><button className="primary" onClick={()=>setCheckout(true)}>Continuar pedido</button></>}</section></main>;
 if(selected)return <main><header><button className="back" onClick={()=>setSelected(null)}>←</button><b className="logo">Citri<span>Food</span></b><button className="cart" onClick={()=>setShowCart(true)}>🛒 {qty}</button></header><section className="restaurantHero"><div>{selected.emoji}</div><h1>{selected.name}</h1><p>⭐ {selected.rating} · {selected.eta} · Envío $ {selected.delivery}</p>{selectedPromos.length>0&&<strong>🔥 {selectedPromos[0].title}</strong>}</section>{selectedPromos.length>0&&<section className="restaurantPromotions" aria-label="Promociones del restaurante"><div className="restaurantPromoHeading"><span>🔥 PROMOCIONES</span><h2>Ofertas de {selected.name}</h2><p>Primero las promociones, después el menú completo.</p></div><div className="restaurantPromoGrid">{selectedPromos.map(p=><article className="restaurantPromoCard" key={p.id}><div className="restaurantPromoEmoji">{p.emoji}</div><div><small>OFERTA ESPECIAL</small><h3>{p.title}</h3><p>{p.description}</p><strong>$ {p.price.toFixed(2)}</strong></div><button onClick={()=>add(p.name,p.price,p.emoji)}>+ Agregar promoción</button></article>)}</div></section>}<h2>Menú completo</h2><div className="menu">{selected.menu.map(([name,price,emoji])=><article key={name}><div><h3>{name}</h3><p>Preparado al momento</p><b>$ {price}</b></div><div className="menuEmoji">{emoji}</div><button onClick={()=>add(name,price,emoji)}>+ Agregar</button></article>)}</div>{qty>0&&<button className="floatingCart" onClick={()=>setShowCart(true)}>Ver carrito · {qty} · $ {total}</button>}</main>;
 return <main><div className="devAccess"><a href="/repartidor">🛵 Repartidor</a><a href="/repartidor/cartera">💰 Cartera</a><a href="/operaciones">🖥️ Operaciones</a><a href="/restaurante">🏪 Restaurante</a><a href="/operaciones/asignacion">⚡ Asignación</a></div><header><div><b className="logo">Citri<span>Food</span></b><small>Entrega local</small></div><button className="cart" onClick={()=>setShowCart(true)}>🛒 {qty}</button></header><section className="hero"><p className="eyebrow">📍 Cerca de ti</p><h1>¿Qué se te antoja hoy?</h1><p>Comida de tus restaurantes favoritos, directo a tu puerta.</p><input value={q} onChange={e=>setQ(e.target.value)} placeholder="🔎 Buscar comida o restaurante"/></section><section><h2>Promociones para ti</h2><div className="promos">{restaurants.flatMap(x=>(promotions[x.name]||[]).filter(p=>p.active!==false&&p.sponsored===true).map(p=>({restaurant:x,promotion:p}))).map(({restaurant:x,promotion:p})=><article className="promo" key={p.id}><span>Patrocinado · DEMO</span><div className="food">{p.emoji||x.emoji}</div><h3>{p.title}</h3><p>{x.name} · $ {p.price.toFixed(2)}</p><button onClick={()=>openRestaurant(x)}>Ver promoción</button></article>)}</div></section><section><div className="sectionTitle"><h2>Restaurantes</h2><span>{shown.length} disponibles</span></div><div className="grid">{shown.map(x=><article className="card" key={x.name}><div className="cover">{x.emoji}{(promotions[x.name]||[]).some(p=>p.active!==false)&&<i>Promoción</i>}</div><div className="pad"><h3>{x.name}</h3><p>{x.cat} · ⭐ {x.rating}</p><p>🛵 {x.eta} · Envío $ {x.delivery}</p><button onClick={()=>openRestaurant(x)}>Ver menú</button></div></article>)}</div></section><nav><b>🏠<small>Inicio</small></b><b>🔎<small>Buscar</small></b><button type="button" onClick={()=>setMyOrders(true)}>🧾<small>Pedidos</small></button><b>👤<small>Cuenta</small></b></nav></main>
}