"use client";
import {useEffect,useState} from "react";
import {getSupabaseBrowserClient,supabaseConfigured} from "../../lib/supabase-client.js";

export default function Cuenta(){
 const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[user,setUser]=useState(null);const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{const s=getSupabaseBrowserClient();if(!s)return;let alive=true;s.auth.getUser().then(({data})=>{if(alive)setUser(data?.user||null)});const {data}=s.auth.onAuthStateChange((_event,session)=>setUser(session?.user||null));return()=>{alive=false;data.subscription.unsubscribe()}},[]);
 const run=async(kind)=>{const s=getSupabaseBrowserClient();if(!s){setMsg("La conexión compartida todavía no está configurada en este despliegue.");return}if(!email.trim()||password.length<6){setMsg("Escribe un correo válido y una contraseña de al menos 6 caracteres.");return}setBusy(true);setMsg("");const result=kind==="signup"?await s.auth.signUp({email:email.trim(),password}):await s.auth.signInWithPassword({email:email.trim(),password});setBusy(false);if(result.error){setMsg(result.error.message);return}setUser(result.data?.user||null);setMsg(kind==="signup"?"Cuenta creada. Si Supabase solicita confirmación, revisa tu correo.":"Sesión iniciada.")};
 const logout=async()=>{const s=getSupabaseBrowserClient();if(s)await s.auth.signOut();setUser(null);setMsg("Sesión cerrada.")};
 return <main><header><a className="back" href="/">←</a><b className="logo">Citri<span>Food</span></b></header><section className="checkout"><h1>Mi cuenta</h1>{!supabaseConfigured()&&<p>Modo local activo. La cuenta compartida se habilitará al configurar Supabase en el despliegue.</p>}{user?<><p><b>Sesión activa</b><br/>{user.email}</p><button className="primary" onClick={logout}>Cerrar sesión</button></>:<><label className="field"><b>Correo</b><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} /></label><label className="field"><b>Contraseña</b><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} /></label><button className="primary" disabled={busy} onClick={()=>run("login")}>{busy?"Procesando…":"Iniciar sesión"}</button><button disabled={busy} onClick={()=>run("signup")}>Crear cuenta</button></>}{msg&&<p className="hint">{msg}</p>}<p><small>Las cuentas se usarán para sincronizar pedidos entre dispositivos. Los cobros reales siguen deshabilitados durante el piloto.</small></p></section></main>
}