import {pruneOrderChats} from "./chat-retention.js";
const KEY="citrifood_mvp";
const ORDER_FLOW={"Nuevo":["Preparando","Rechazado","Cancelado"],"Preparando":["Listo","Rechazado"],"Listo":["Esperando repartidor","En entrega"],"Esperando repartidor":["En entrega"],"En entrega":["Entregado"],"Entregado":[],"Rechazado":[],"Cancelado":[]};
export function canTransitionOrder(from,to){return !!ORDER_FLOW[from]?.includes(to)}
export function loadMvp(){if(typeof window==="undefined")return {orders:[]};try{const data=JSON.parse(localStorage.getItem(KEY)||"null");if(!data||!Array.isArray(data.orders))return {orders:[]};const clean=pruneOrderChats(data);if(clean.changed)localStorage.setItem(KEY,JSON.stringify(clean.state));return clean.state}catch{return {orders:[]}}}
export function saveMvp(value){if(typeof window!=="undefined"){const clean=pruneOrderChats(value).state;localStorage.setItem(KEY,JSON.stringify(clean));window.dispatchEvent(new Event("citrifood:change"))}return pruneOrderChats(value).state}
export function clearMvp(){if(typeof window!=="undefined"){localStorage.removeItem(KEY);window.dispatchEvent(new Event("citrifood:change"))}}
export function createOrder(data){const now=new Date().toISOString();return {...data,id:"CF-"+Date.now().toString(36).toUpperCase()+"-"+Math.random().toString(36).slice(2,6).toUpperCase(),createdAt:now,status:"Nuevo",statusHistory:[{status:"Nuevo",at:now}]}}
export function addOrder(data){const order=createOrder(data);const state=loadMvp();saveMvp({...state,orders:[order,...state.orders]});return order}
export function updateOrder(id,changes){const state=loadMvp();let updated=null;const orders=state.orders.map(order=>{if(order.id!==id)return order;if(changes.status&&changes.status!==order.status&&!canTransitionOrder(order.status,changes.status))return order;if(changes.status==="Entregado"&&order.deliveryIssue&&!order.deliveryIssue.resolvedAt)return order;const now=new Date().toISOString();const statusChanged=changes.status&&changes.status!==order.status;updated={...order,...changes,id:order.id,createdAt:order.createdAt,updatedAt:now,statusHistory:statusChanged?[...(order.statusHistory||[]),{status:changes.status,at:now}]:order.statusHistory||[]};return updated});if(updated)saveMvp({...state,orders});return updated}
export function cancelOrder(id){const order=getOrder(id);if(!order||order.status!=="Nuevo")return null;return updateOrder(id,{status:"Cancelado",cancelledAt:new Date().toISOString(),cancelledBy:"Cliente (demo)"})}
export function getOrder(id){return loadMvp().orders.find(order=>order.id===id)||null}
export function subscribeOrders(callback){if(typeof window==="undefined")return()=>{};window.addEventListener("storage",callback);window.addEventListener("citrifood:change",callback);return()=>{window.removeEventListener("storage",callback);window.removeEventListener("citrifood:change",callback)}}

export function reportDeliveryIssue(id,description){const order=getOrder(id);const detail=String(description||"").trim();if(!order||order.status!=="En entrega"||order.deliveryIssue&&!order.deliveryIssue.resolvedAt||!detail||detail.length>250)return null;const at=new Date().toISOString();return updateOrder(id,{deliveryIssue:{description:detail,reportedAt:at,resolvedAt:null},deliveryIssueHistory:[...(order.deliveryIssueHistory||[]),{description:detail,reportedAt:at,resolvedAt:null}]})}
export function resolveDeliveryIssue(id){const order=getOrder(id);if(!order?.deliveryIssue||order.deliveryIssue.resolvedAt)return null;const at=new Date().toISOString();return updateOrder(id,{deliveryIssue:{...order.deliveryIssue,resolvedAt:at},deliveryIssueHistory:(order.deliveryIssueHistory||[]).map((issue,i,all)=>i===all.length-1?{...issue,resolvedAt:at}:issue)})}
