"use client";
import {useEffect,useState} from "react";
import {loadMvp,resolveDeliveryIssue,subscribeOrders,updateOrder} from "../../../lib/mvp-store.js";
import {loadCouriers,updateCourier} from "../../../lib/courier-registry.js";
import "./orders.css";
import {ordersToCsv} from "../../../lib/order-export.js";
import {orderMessages} from "../../../lib/order-chat.js";
import {assignOperationsSharedCourier,fetchOperationsOrderAudit,fetchOperationsPinSecurity,fetchOperationsSharedOrders,resetOperationsPinLock} from "../../../lib/operations-shared-orders.js";
import {fetchOperationsCashBalances} from "../../../lib/operations-shared-cash.js";

const seed=[
 {id:"CF-DEMO-3",restaurant:"Tacos El Centro",customer:"María (ejemplo)",courier:"Sin asignar",status:"Preparando",payment:"Efectivo",total:245},
 {id:"CF-DEMO-4",restaurant:"Burger House",customer:"José (ejemplo)",courier:"Juan Pérez",status:"En entrega",payment:"Tarjeta",total:210}
];
const statuses=["Todos","Nuevo","Preparando","Listo","Esperando repartidor","En entrega","Entregado","Rechazado","Cancelado"];

export default function Pedidos(){
 const[filter,setFilter]=useState("Todos");
 const[query,setQuery]=useState("");
 const[actual,setActual]=useState([]);const[shared,setShared]=useState([]);const[sharedNotice,setSharedNotice]=useState("");const[sharedCouriers,setSharedCouriers]=useState([]);const[assignment,setAssignment]=useState({});const[pinSecurity,setPinSecurity]=useState([]);const[audit,setAudit]=useState({});
 const[expanded,setExpanded]=useState(null);const[issuesOnly,setIssuesOnly]=useState(false);const[supportOnly,setSupportOnly]=useState(false);
 useEffect(()=>{const refresh=()=>setActual(loadMvp().orders);refresh();return subscribeOrders(refresh)},[]);
 useEffect(()=>{let active=true;const sync=async()=>{const [r,cash,pins]=await Promise.all([fetchOperationsSharedOrders(),fetchOperationsCashBalances(),fetchOperationsPinSecurity()]);if(!active)return;if(r.ok){setShared(r.orders);setSharedNotice("Pedidos compartidos sincronizados.")}else setSharedNotice(r.error||"No se pudieron consultar los pedidos compartidos.");if(cash.ok)setSharedCouriers(cash.drivers);if(pins.ok)setPinSecurity(pins.items)};sync();const timer=setInterval(sync,10000);return()=>{active=false;clearInterval(timer)}},[]);
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get("order");if(id){setQuery(id);setExpanded(id)}},[]);
 const resolveNoResponse=(order)=>{const current=loadMvp().orders.find(x=>x.id===order.id);if(!current||current.status!=="En entrega"||current.supportReview?.type!=="customer_no_response"||current.supportReview?.status!=="Pendiente")return;order=current;const at=new Date().toISOString();const updated=updateOrder(order.id,{status:"Cancelado",supportReview:{...order.supportReview,status:"Atendido",resolution:"Cliente sin respuesta",resolvedAt:at},cancelledAt:at,cancelReason:"Cliente sin respuesta tras protocolo de contacto",deliveryEvents:[...(order.deliveryEvents||[]),{type:"support_no_response_closed",at}]});if(updated&&order.courierId){const driver=loadCouriers().find(x=>x.id===order.courierId);if(driver){const remaining=Math.max(0,(driver.activeOrders||1)-1);const finishing=driver.endingShift===true;if(finishing&&remaining===0)updateCourier(driver.id,{activeOrders:0,online:false,available:true,endingShift:false,status:"Desconectado"});else updateCourier(driver.id,{activeOrders:remaining,status:finishing?"Terminando jornada":remaining>0?"En entrega":"Disponible"})}}};
 const toggleAudit=async(orderId)=>{if(audit[orderId]){setAudit(v=>({...v,[orderId]:null}));return}const r=await fetchOperationsOrderAudit(orderId);if(!r.ok){setSharedNotice(r.error||"No se pudo consultar la auditoría.");return}setAudit(v=>({...v,[orderId]:r.items}))};
 const resetPin=async(orderId)=>{if(!window.confirm("¿Desbloquear los intentos de PIN de este pedido?"))return;const r=await resetOperationsPinLock(orderId);if(!r.ok){setSharedNotice(r.error||"No se pudo desbloquear.");return}setPinSecurity(v=>v.filter(x=>x.order_id!==orderId));setSharedNotice("PIN desbloqueado. El repartidor puede volver a intentarlo.")};
 const assignShared=async(order)=>{const courierId=assignment[order.id];if(!courierId)return;setSharedNotice("Asignando repartidor…");const r=await assignOperationsSharedCourier(order.id,courierId);if(!r.ok){setSharedNotice(r.error||"No se pudo asignar el repartidor.");return}const refreshed=await fetchOperationsSharedOrders();if(refreshed.ok)setShared(refreshed.orders);setSharedNotice("Repartidor asignado. El pedido pasó a Esperando repartidor.")};
 const downloadCsv=()=>{const content=ordersToCsv(rows.filter(o=>!o.id.startsWith("CF-DEMO-")));const blob=new Blob([content],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="citrifood-pedidos-demo-"+new Date().toISOString().slice(0,10)+".csv";document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const sharedRows=shared.map(o=>({...o,id:o.id,restaurant:o.restaurant_name,customer:"Cliente de cuenta",address:o.delivery_address,deliveryNotes:o.delivery_notes,paymentMethod:o.payment_method,total:Number(o.total_cents||0)/100,createdAt:o.created_at,courier:o.courier_id?(sharedCouriers.find(c=>c.user_id===o.courier_id)?.display_name||"Repartidor asignado"):"Sin asignar",shared:true}));
 const all=[...sharedRows,...actual,...seed];
 const search=query.trim().toLocaleLowerCase("es-MX");
 const rows=all.filter(x=>(!issuesOnly||x.deliveryIssue&&!x.deliveryIssue.resolvedAt)&&(!supportOnly||x.supportReview?.status==="Pendiente")&&(filter==="Todos"||x.status===filter)&&(!search||[x.id,x.restaurant,x.customer,x.address,x.deliveryNotes,x.courier].some(v=>String(v||"").toLocaleLowerCase("es-MX").includes(search))));
 return <main className="ordersAdmin">
  <header><a href="/operaciones">← Operaciones</a><b>CitriFood · Pedidos</b></header>
  <h1>Pedidos</h1>
  <p>Pedidos compartidos de Supabase, pedidos locales de este navegador y ejemplos identificados.</p>{sharedNotice&&<p><b>Compartidos:</b> {sharedNotice} · {shared.length} pedido(s)</p>}
  <label className="orderSearch">Buscar pedido, restaurante, cliente o dirección
   <input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ej. CF-, Burger House o Centro"/>
  </label>
  <div className="filters">{statuses.map(x=><button type="button" className={filter===x?"on":""} onClick={()=>setFilter(x)} key={x}>{x} ({x==="Todos"?all.length:all.filter(o=>o.status===x).length})</button>)}</div>
  <label className="issueFilter"><input type="checkbox" checked={issuesOnly} onChange={e=>setIssuesOnly(e.target.checked)}/> Solo incidencias pendientes ({actual.filter(o=>o.deliveryIssue&&!o.deliveryIssue.resolvedAt).length})</label><label className="issueFilter"><input type="checkbox" checked={supportOnly} onChange={e=>setSupportOnly(e.target.checked)}/> Cliente sin respuesta / soporte ({actual.filter(o=>o.supportReview?.type==="customer_no_response"&&o.supportReview?.status==="Pendiente").length})</label><div className="orderToolbar"><p className="orderCount">{rows.length} pedidos mostrados</p><button type="button" disabled={!rows.some(o=>!o.id.startsWith("CF-DEMO-"))} onClick={downloadCsv}>↓ Exportar pedidos filtrados (CSV)</button></div>
  <section>{rows.length===0&&<p>No hay pedidos que coincidan con la búsqueda o el estado.</p>}
   {rows.map(x=><article key={x.id}>
    <div><small>{x.id}{x.id.startsWith("CF-DEMO-")?" · EJEMPLO":""}</small><h2>{x.restaurant}</h2><p>{x.customer} · {x.paymentMethod||x.payment} · $ {x.total}</p></div>
    <div className="orderActions"><strong>{x.status}</strong>{x.deliveryIssue&&!x.deliveryIssue.resolvedAt&&<b className="issueBadge">⚠️ Incidencia pendiente</b>}{x.supportReview?.status==="Pendiente"&&<b className="issueBadge">🆘 Soporte pendiente</b>}<small>{x.courier||"Sin asignar"}</small>
     {x.shared&&x.status==="Listo"&&<div><select value={assignment[x.id]||""} onChange={e=>setAssignment(v=>({...v,[x.id]:e.target.value}))}><option value="">Seleccionar repartidor</option>{sharedCouriers.filter(c=>c.active).map(c=>{const cash=x.payment_method==="Efectivo (simulado)",activeOrders=Number(c.active_orders||0),cashOk=!cash||Number(c.available_cash_cents||0)>=Number(x.total_cents||0),can=activeOrders<4&&cashOk;return <option key={c.user_id} value={c.user_id} disabled={!can}>{c.display_name||"Repartidor"} · {activeOrders}/4 activos · {cash?"$"+(Number(c.available_cash_cents||0)/100).toFixed(2)+" disponible":"tarjeta"}{activeOrders>=4?" · LLENO":!cashOk?" · SIN CUPO":""}</option>})}</select><button type="button" disabled={!assignment[x.id]} onClick={()=>assignShared(x)}>Asignar</button></div>}{x.shared&&x.status==="Esperando repartidor"&&<small>Repartidor compartido asignado.</small>}{!x.shared&&!x.id.startsWith("CF-DEMO-")&&["Listo","Esperando repartidor"].includes(x.status)&&<small>Asignación gestionada por el flujo local de demostración.</small>}
     <button type="button" className="detailButton" aria-expanded={expanded===x.id} onClick={()=>setExpanded(v=>v===x.id?null:x.id)}>{expanded===x.id?"Ocultar detalle":"Ver detalle"}</button>
    </div>
    {expanded===x.id&&<div className="orderDetails">
     {x.id.startsWith("CF-DEMO-")?<p>Esta tarjeta es ilustrativa y no contiene datos de un cliente real.</p>:<>
      <p><b>Dirección:</b> {x.address||"No registrada"}</p>{x.deliveryNotes&&<p><b>Indicaciones de entrega:</b> {x.deliveryNotes}</p>}
      <p><b>Creado:</b> {x.createdAt?new Date(x.createdAt).toLocaleString("es-MX"):"Sin fecha"}</p>{x.shared&&<div className="opsIssue"><h3>Seguimiento compartido</h3>{(()=>{const sec=pinSecurity.find(p=>p.order_id===x.id);return sec?<p><b>🔐 PIN:</b> {sec.failed_attempts} intento(s) fallido(s){sec.locked_until&&new Date(sec.locked_until)>new Date()?<> · bloqueado hasta {new Date(sec.locked_until).toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit"})} <button type="button" onClick={()=>resetPin(x.id)}>Desbloquear</button></>:null}</p>:null})()}<p>{x.ready_at?"✓":"○"} Restaurante marcó listo{x.ready_at?" · "+new Date(x.ready_at).toLocaleString("es-MX"):""}</p><p>{x.courier_id?"✓":"○"} Repartidor asignado</p><p>{x.restaurant_arrival_verified?"✓":"○"} Llegada al restaurante verificada{x.arrived_restaurant_at?" · "+new Date(x.arrived_restaurant_at).toLocaleString("es-MX"):""}</p><p>{x.picked_up_at?"✓":"○"} Pedido recogido{x.picked_up_at?" · "+new Date(x.picked_up_at).toLocaleString("es-MX"):""}</p><p>{x.customer_arrival_verified?"✓":"○"} Llegada al cliente verificada{x.arrived_customer_at?" · "+new Date(x.arrived_customer_at).toLocaleString("es-MX"):""}</p><p>{x.status==="Entregado"?"✓":"○"} Entregado</p><button type="button" onClick={()=>toggleAudit(x.id)}>{audit[x.id]?"Ocultar auditoría":"Ver auditoría"}</button>{audit[x.id]&&<div><b>Auditoría de Operaciones</b>{audit[x.id].length===0?<p>Sin acciones registradas.</p>:audit[x.id].map(a=><p key={a.id}>{a.action==="reset_delivery_pin_lock"?"🔓 Desbloqueo de PIN":a.action} · {new Date(a.created_at).toLocaleString("es-MX")} · usuario {String(a.operations_user_id).slice(0,8)}</p>)}</div>}</div>}
      <p><b>Envío:</b> $ {x.deliveryFee??"No registrado"}</p>
      {x.supportReview?.type==="customer_no_response"&&<div className="opsIssue"><h3>🆘 Cliente sin respuesta</h3><p>Intentos registrados: {x.noResponse?.messages||0} mensaje(s) · {x.noResponse?.calls||0} llamada(s).</p>{x.noResponse?.startedAt&&<small>Primer intento: {new Date(x.noResponse.startedAt).toLocaleString("es-MX")}</small>}<p><b>Estado:</b> {x.supportReview.status}</p>{x.supportReview.status==="Pendiente"&&x.status==="En entrega"&&<button type="button" onClick={()=>resolveNoResponse(x)}>Cerrar caso · cliente sin respuesta</button>}{x.supportReview.status==="Pendiente"&&x.status!=="En entrega"&&<small>El pedido cambió de estado; requiere revisión manual antes de cerrar el caso.</small>}</div>}{x.deliveryIssue&&<div className="opsIssue"><h3>⚠️ Incidencia de entrega</h3><p>{x.deliveryIssue.description}</p><small>Reportada: {new Date(x.deliveryIssue.reportedAt).toLocaleString("es-MX")}</small>{x.deliveryIssue.resolvedAt?<p>Atendida: {new Date(x.deliveryIssue.resolvedAt).toLocaleString("es-MX")}</p>:<button type="button" onClick={()=>resolveDeliveryIssue(x.id)}>Marcar como atendida (demo)</button>}</div>}{x.deliveryIssueHistory?.length>1&&<details className="opsIssueHistory"><summary>Incidencias anteriores ({x.deliveryIssueHistory.length-1})</summary>{x.deliveryIssueHistory.slice(0,-1).map((issue,i)=><p key={i}>{issue.description} · {issue.resolvedAt?"Atendida":"Pendiente"}</p>)}</details>}<h3>Productos</h3>
      <ul>{(Array.isArray(x.items)?x.items:[]).map((item,i)=><li key={i}>{item.qty} × {item.name} · $ {(item.price*item.qty).toFixed(2)}</li>)}</ul>
      <details className="opsChatEvidence"><summary>💬 Chat del pedido · evidencia temporal ({orderMessages(x).length} mensajes)</summary><p>Los mensajes se conservan hasta 15 días desde su envío en este navegador de prueba.</p>{orderMessages(x).length===0?<p>No hay mensajes vigentes.</p>:orderMessages(x).map(m=><article key={m.id}><b>{m.role}</b><p>{m.body}</p><small>{new Date(m.at).toLocaleString("es-MX")}</small></article>)}</details><h3>Movimientos</h3>
      <ol>{(x.statusHistory||[]).map((event,i)=><li key={i}>{event.status} · {new Date(event.at).toLocaleString("es-MX")}</li>)}</ol>
     </>}
    </div>}
   </article>)}
  </section>
 </main>;
}
