"use client";
import {useEffect,useState} from "react";
import "./courier.css";
import OrderChat from "../../components/order-chat.js";
import {loadMvp,reportDeliveryIssue,subscribeOrders,updateOrder} from "../../lib/mvp-store.js";
import {closeCourierDay} from "../../lib/finance.js";
const offers=[
{id:"CF-1052",restaurant:"Taco Chuy",pickup:"Centro",destination:"Infonavit",pay:"Tarjeta",earning:38,route:"+4 min",fit:96},
{id:"CF-1053",restaurant:"Sergio's Pizza",pickup:"Centro",destination:"Infonavit",pay:"Tarjeta",earning:42,route:"+6 min",fit:92},
{id:"CF-1054",restaurant:"Taco Lin",pickup:"Centro",destination:"Infonavit",pay:"Efectivo",total:120,earning:35,route:"+7 min",fit:89}
];
export default function Repartidor(){const[assigned,setAssigned]=useState([]);const[issueDrafts,setIssueDrafts]=useState({});const[issueEditing,setIssueEditing]=useState(null);const[online,setOnline]=useState(true),[draining,setDraining]=useState(false),[auto,setAuto]=useState(true),[active,setActive]=useState([offers[0]]),[offer,setOffer]=useState(offers[1]),[seconds,setSeconds]=useState(25),[notice,setNotice]=useState("");
useEffect(()=>{const refresh=()=>setAssigned(loadMvp().orders.filter(o=>o.courier==="Juan Pérez (demo)"&&o.status==="En entrega"));refresh();return subscribeOrders(refresh)},[]);
const inProgress=active.length+assigned.length;
const demoEarnings=312,demoCash=540,demoPreviousDebt=180;
const settlement=closeCourierDay({deliveryEarnings:demoEarnings,cashCollected:demoCash,previousWalletDebt:demoPreviousDebt});
useEffect(()=>{if(draining&&inProgress===0){setOnline(false);setDraining(false);setNotice("Todos los pedidos fueron entregados. Ya estás desconectado.")}},[draining,inProgress]);
function nextOffer(current){return offers.find(x=>!active.some(a=>a.id===x.id)&&x.id!==current?.id)||null}
function accept(){if(!draining&&active.length<4&&offer){const current=offer;setActive(v=>[...v,current]);setNotice("Pedido "+current.id+" aceptado");setOffer(nextOffer(current));setSeconds(25)}}
function reject(){if(offer){setNotice("Pedido rechazado. Se registra como respuesta, no como cancelación.");setOffer(nextOffer(offer));setSeconds(25)}}
function toggleConnection(){if(!online){setOnline(true);setDraining(false);setNotice("Estás conectado y disponible para recibir pedidos.");if(!offer)setOffer(nextOffer(null));return}if(inProgress>0){setDraining(true);setOffer(null);setNotice("Ya no recibirás pedidos nuevos. Te desconectaremos automáticamente al terminar los pedidos en curso.");return}setOnline(false);setDraining(false);setOffer(null);setNotice("Te desconectaste correctamente.")}
useEffect(()=>{setSeconds(25)},[offer?.id]);
useEffect(()=>{if(!offer||!online||draining)return;if(auto&&offer.fit>=90&&active.length<4){const t=setTimeout(()=>accept(),1200);return()=>clearTimeout(t)}const t=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(t);setNotice("Oferta sin respuesta. Impacto mínimo acumulativo en desempeño.");setOffer(nextOffer(offer));return 25}return s-1}),1000);return()=>clearInterval(t)},[offer?.id,online,draining,auto,active.length]);
return <main className="courier"><header><div><b>Citri<span>Food</span></b><small>Repartidor · Juan</small></div><button className={online?(draining?"finishing":"online"):"offline"} onClick={toggleConnection}>{!online?"○ Desconectado":draining?"⏳ Dejar de recibir y desconectarse":"● Conectado"}</button></header>
{draining&&<div className="disconnectBanner"><b>Terminando jornada</b><span>No recibirás pedidos nuevos. Completa tus {inProgress} pedido{inProgress===1?"":"s"} en curso y CitriFood te desconectará automáticamente.</span></div>}
<section className="top"><div><small>GANANCIAS HOY</small><h1>$ {demoEarnings.toFixed(2)}</h1><a href="/repartidor/cartera">Ver cartera →</a></div><label className="auto"><span><b>Aceptación automática</b><small>Prioridad adicional en pedidos compatibles</small></span><input type="checkbox" checked={auto} disabled={draining||!online} onChange={e=>setAuto(e.target.checked)}/></label></section>
{offer&&online&&!draining&&<section className="offer"><div className="timer">{seconds}<small>seg</small></div><div><small>NUEVO PEDIDO · {offer.fit}% compatible con tu ruta</small><h2>{offer.restaurant}</h2><p>📍 {offer.pickup} → {offer.destination} · {offer.route}</p><p><b>Ganas ${offer.earning}</b> · {offer.pay}{offer.total?" · Cliente paga $"+offer.total:""}</p></div><div className="offerBtns"><button onClick={reject}>Rechazar</button><button onClick={accept}>Aceptar</button></div></section>}
{notice&&<p className="dispatchNotice">{notice}</p>}<section className="courierSettlement"><div><small>CORTE NOCTURNO · DEMO</small><h2>Depósito estimado $ {settlement.courierPayout.toFixed(2)}</h2></div><div className="courierSettlementGrid"><span>Ganancias <b>$ {settlement.earnings.toFixed(2)}</b></span><span>Efectivo + cartera <b>$ {settlement.totalDebt.toFixed(2)}</b></span><span>Aplicado a cartera <b>-$ {settlement.appliedToWallet.toFixed(2)}</b></span><span>Saldo pendiente <b>$ {settlement.debtAfter.toFixed(2)}</b></span></div><p>El corte se realiza al terminar el día y la dispersión se prepara alrededor de las 02:00. Esta pantalla todavía no mueve dinero real.</p></section>{assigned.length>0&&<section className="route"><h2>📦 Pedidos asignados desde Operaciones (demo)</h2>{assigned.map(o=><article key={o.id}><div><b>{o.id} · {o.restaurant}</b><p>📍 {o.address}</p>{o.deliveryNotes&&<p className="courierNotes">📝 {o.deliveryNotes}</p>}<small>{o.paymentMethod} · Total $ {o.total}</small></div><div className="courierOrderActions"><button disabled={Boolean(o.deliveryIssue&&!o.deliveryIssue.resolvedAt)} onClick={()=>updateOrder(o.id,{status:"Entregado",deliveredAt:new Date().toISOString()})}>Confirmar entrega</button><button type="button" disabled={Boolean(o.deliveryIssue&&!o.deliveryIssue.resolvedAt)} className="courierIssueButton" onClick={()=>setIssueEditing(v=>v===o.id?null:o.id)}>⚠️ Incidencia</button></div><div className="courierChat"><OrderChat order={o} role="Repartidor"/></div>{o.deliveryIssue&&!o.deliveryIssue.resolvedAt&&<p className="courierIssueAlert">Primero debe atenderse la incidencia para confirmar la entrega.</p>}{o.deliveryIssue&&<p className="courierIssueAlert"><b>Incidencia:</b> {o.deliveryIssue.description} · {o.deliveryIssue.resolvedAt?"Atendida por Operaciones":"Pendiente de Operaciones"}</p>}{issueEditing===o.id&&<form className="courierIssueForm" onSubmit={e=>{e.preventDefault();if(reportDeliveryIssue(o.id,issueDrafts[o.id])){setIssueEditing(null);setIssueDrafts(d=>({...d,[o.id]:""}))}}}><label>Describe el problema<textarea required maxLength={250} value={issueDrafts[o.id]||""} onChange={e=>setIssueDrafts(d=>({...d,[o.id]:e.target.value}))} placeholder="Ej. No encuentro el domicilio"/></label><button type="submit" disabled={!issueDrafts[o.id]?.trim()}>Enviar a Operaciones (demo)</button></form>}</article>)}</section>}<section><div className="routeHead"><div><small>RUTA ACTIVA</small><h2>{active.length} de 4 pedidos</h2></div><span>{draining?"Cerrando jornada · sin pedidos nuevos":"Orden de demostración · ruta GPS pendiente"}</span></div><div className="route">{active.map((x,i)=><article key={x.id}><i>{i+1}</i><div><b>{i===0?"Recoger":"Siguiente"} · {x.restaurant}</b><p>{x.pickup} → {x.destination}</p><small>{x.id} · {x.pay} · Ganancia ${x.earning}</small></div><a className="viewOrder" href="/repartidor/pedido">Ver</a></article>)}</div></section>
<nav><button>🏠<small>Inicio</small></button><button>🗺️<small>Ruta</small></button><a href="/repartidor/cartera">💰<small>Cartera</small></a><a href="/repartidor/perfil">👤<small>Perfil</small></a></nav></main>}